detectors:
  IrresponsibleModule:
    enabled: false

  InstanceVariableAssumption:
    enabled: false

  TooManyStatements:
    max_statements: 20

exclude_paths:
  - db/migrate
  - app/helpers
  - test
  - config
